name: Update Smart Meter Scripts

on:
  schedule:
    - cron: '0 2 * * *'  # Täglich um 2 Uhr UTC
  workflow_dispatch:     # Manueller Trigger

jobs:
  update-scripts:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4
    
    - name: Run script crawler
      run: |
        python tools/update_scripts.py
    
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --staged --quiet || git commit -m "Auto-update scripts $(date)"
        git push
